language: python
python:
  - "2.7"

install:
  - pip install coverage
  - pip install prettytable

script: python setup.py test

after_success:
  - coverage -x setup.py test
  - coverage -rm
sadfl;kjasdfgjdspalif oldsjfalsdijf posdaj  
